const express = require("express");
const controller = require("./accesos.controller");
const { requiereAuth } = require("../../middleware/authMiddleware");
const { validarUuidParam } = require("../../middleware/validateMiddleware");
const router = express.Router();
router.use(requiereAuth);
router.get("/predios/:predioId/accesos", validarUuidParam("predioId"), controller.list);
router.post("/predios/:predioId/accesos", validarUuidParam("predioId"), controller.add);
router.patch("/predios/:predioId/accesos/:usuarioId", validarUuidParam("predioId"), validarUuidParam("usuarioId"), controller.update);
router.delete("/predios/:predioId/accesos/:usuarioId", validarUuidParam("predioId"), validarUuidParam("usuarioId"), controller.remove);
module.exports = router;
