const express = require("express");
const controller = require("./circuitos.controller");
const { requiereAuth } = require("../../middleware/authMiddleware");
const { validarUuidParam } = require("../../middleware/validateMiddleware");
const router = express.Router();
router.use(requiereAuth);
router.get("/dispositivos/:dispositivoId/circuitos", validarUuidParam("dispositivoId"), controller.list);
router.post("/dispositivos/:dispositivoId/circuitos", validarUuidParam("dispositivoId"), controller.create);
router.get("/circuitos/:circuitoId", validarUuidParam("circuitoId"), controller.get);
router.patch("/circuitos/:circuitoId", validarUuidParam("circuitoId"), controller.update);
router.delete("/circuitos/:circuitoId", validarUuidParam("circuitoId"), controller.remove);
module.exports = router;
