import { computed, ref } from 'vue';
import { tiempoRealApi } from '../services/tiempoRealApi';

const WINDOW_MINUTES = 5;
export const realtimeMetrics = [
  { key: 'energia', label: 'Energía', unit: 'kWh', decimals: 3 }, { key: 'potencia', label: 'Potencia', unit: 'W', decimals: 2 },
  { key: 'voltaje', label: 'Voltaje', unit: 'V', decimals: 2 }, { key: 'corriente', label: 'Corriente', unit: 'A', decimals: 2 },
  { key: 'factor_potencia', label: 'Factor de potencia', unit: 'FP', decimals: 3 },
];
export const realtimeCharts = [
  { key: 'energia', title: 'Energía consumida', unit: 'kWh', color: '#39FF14', explanation: 'Muestra la energía reportada por cada circuito en cada lectura. Los huecos indican que no llegó una medición.' },
  { key: 'potencia', title: 'Potencia utilizada', unit: 'W', color: '#DFFF00', explanation: 'Muestra cuánta potencia se estaba utilizando en cada lectura. Un valor más alto indica mayor demanda en ese momento.' },
  { key: 'voltaje', title: 'Fuerza eléctrica', unit: 'V', color: '#FF3131', explanation: 'Muestra la fuerza eléctrica registrada en cada lectura y permite observar si se mantiene estable.' },
  { key: 'corriente', title: 'Cantidad de electricidad', unit: 'A', color: '#7B2CFF', explanation: 'Muestra cuánta electricidad circulaba por el circuito en cada lectura.' },
  { key: 'factor_potencia', title: 'Aprovechamiento eléctrico', unit: 'FP', color: '#FF6A00', explanation: 'Muestra qué tan bien se estaba aprovechando la electricidad en cada lectura.' },
];
function toMeasurement(item, time) { return { id: item.id || `${time}-${item.circuito_id || item.circuito}`, created_at: time, circuito_id: item.circuito_id, potencia: Number(item.potencia), energia: Number(item.energia), voltaje: Number(item.voltaje), corriente: Number(item.corriente), factor_potencia: Number(item.factor_potencia) }; }
function normalizeRecord(panel, device, circuit, measurements) { const ordered = (measurements || []).map((item) => toMeasurement(item, item.created_at)).filter((item) => Number.isFinite(new Date(item.created_at).getTime())).sort((a, b) => new Date(a.created_at) - new Date(b.created_at)); return { panel, device, circuit, measurements: ordered, latest: ordered.at(-1) || null }; }
export function useRealtimeData(predioId) {
  const loading = ref(false); const loadError = ref(''); const panels = ref([]); const records = ref([]); let requestVersion = 0; let refreshing = false;
  async function loadData() { const propertyId = predioId.value; if (!propertyId) return; const version = ++requestVersion; loading.value = true; loadError.value = ''; records.value = []; try { const panelList = await tiempoRealApi.listarPaneles(propertyId); if (version !== requestVersion) return; panels.value = Array.isArray(panelList) ? panelList : []; const built = []; for (const panel of panels.value) { const devices = await tiempoRealApi.listarDispositivos(panel.id); for (const device of Array.isArray(devices) ? devices : []) { const circuits = await tiempoRealApi.listarCircuitos(device.id); for (const circuit of Array.isArray(circuits) ? circuits : []) { const from = new Date(Date.now() - WINDOW_MINUTES * 60 * 1000 - 15000).toISOString(); built.push(normalizeRecord(panel, device, circuit, await tiempoRealApi.listarMediciones(circuit.id, from))); } } } if (version === requestVersion) records.value = built; } catch { if (version === requestVersion) loadError.value = 'No se pudo cargar la información de tiempo real. Intenta nuevamente.'; } finally { if (version === requestVersion) loading.value = false; } }
  async function refreshMeasurements() { if (refreshing || loading.value || !predioId.value || !records.value.length) return; refreshing = true; try { const from = new Date(Date.now() - WINDOW_MINUTES * 60 * 1000 - 15000).toISOString(); const currentRecords = records.value.map((record) => ({ ...record })); const measurements = await Promise.all(currentRecords.map((record) => tiempoRealApi.listarMediciones(record.circuit.id, from))); records.value = currentRecords.map((record, index) => normalizeRecord(record.panel, record.device, record.circuit, measurements[index])); } catch { loadError.value = 'No se pudieron actualizar las mediciones. Se reintentará automáticamente.'; } finally { refreshing = false; } }
  function applyLivePayload(payload) { const time = payload?.timestamp || new Date().toISOString(); for (const item of payload?.medidores || []) { const record = records.value.find((candidate) => candidate.circuit.id === item.id_circuito); if (!record) continue; const measurement = toMeasurement(item, time); record.measurements = [...record.measurements.filter((old) => old.id !== measurement.id), measurement].filter((old) => Date.now() - new Date(old.created_at).getTime() <= WINDOW_MINUTES * 60 * 1000 + 15000).sort((a, b) => new Date(a.created_at) - new Date(b.created_at)); record.latest = record.measurements.at(-1) || null; } }
  function chartSeries(metric, visibleRecords, rangeMinutes) { const cutoff = Date.now() - rangeMinutes.value * 60 * 1000; return visibleRecords.value.map((record) => { const seen = new Set(); const points = record.measurements.map((item) => { const time = new Date(item.created_at).getTime(); const value = Number(item[metric]); const identity = item.id || `${time}-${item.circuito_id || record.circuit.id}`; if (seen.has(identity) || !Number.isFinite(time) || time < cutoff || !Number.isFinite(value)) return null; seen.add(identity); return { time: new Date(time).toISOString(), value }; }).filter(Boolean).sort((a, b) => new Date(a.time) - new Date(b.time)); return { label: `${panelLabel(record.panel)} · ${record.circuit.nombre}`, points }; }).filter((series) => series.points.length); }
  return { loading, loadError, panels, records, loadData, refreshMeasurements, applyLivePayload, chartSeries };
}
export function panelLabel(panel) { return `${panel.nombre} · ${panel.tipo_panel === 'Secundario' ? 'Panel secundario' : 'Panel principal'}`; }
export function formatMetric(value, decimals) { return value === null || value === undefined || Number.isNaN(Number(value)) ? '—' : Number(value).toLocaleString('es-CO', { minimumFractionDigits: decimals, maximumFractionDigits: decimals }); }
