const express = require("express");
const controller = require("./paneles.controller");
const { requiereAuth } = require("../../middleware/authMiddleware");
const { validarUuidParam } = require("../../middleware/validateMiddleware");
const router = express.Router();
router.use(requiereAuth);
router.get("/predios/:predioId/paneles", validarUuidParam("predioId"), controller.list);
router.post("/predios/:predioId/paneles", validarUuidParam("predioId"), controller.create);
router.get("/paneles/:panelId", validarUuidParam("panelId"), controller.get);
router.patch("/paneles/:panelId", validarUuidParam("panelId"), controller.update);
router.delete("/paneles/:panelId", validarUuidParam("panelId"), controller.remove);
module.exports = router;
