const express = require("express");
const controller = require("./predios.controller");
const { requiereAuth } = require("../../middleware/authMiddleware");
const { validarUuidParam } = require("../../middleware/validateMiddleware");
const router = express.Router();
router.use(requiereAuth);
router.get("/", controller.list);
router.post("/", controller.create);
router.get("/:predioId", validarUuidParam("predioId"), controller.get);
router.patch("/:predioId", validarUuidParam("predioId"), controller.update);
router.delete("/:predioId", validarUuidParam("predioId"), controller.remove);
module.exports = router;
