<template>
  <div class="realtime-view">
    <header class="welcome"><div><span class="eyebrow">Monitoreo en vivo</span><h2>Tiempo real</h2><p>{{ predio.predioActual.value?.nombre || 'Selecciona un predio para comenzar' }}</p></div><StatusBadge :tone="realtime.status.value === 'conectado' ? 'success' : realtime.status.value === 'reconectando' ? 'warning' : 'neutral'">{{ realtime.status.value }}</StatusBadge></header>
    <ErrorState v-if="loadError" :message="loadError" retry @retry="loadData"/>
    <LoadingState v-else-if="loading" message="Cargando paneles, circuitos y mediciones…"/>
    <EmptyState v-else-if="!predio.predioId.value" title="Selecciona un predio" message="Elige un predio en la barra superior para consultar sus mediciones."/>
    <EmptyState v-else-if="!records.length" title="Este predio aún no tiene circuitos" message="Cuando existan paneles, dispositivos y circuitos disponibles aparecerán aquí."/>
    <template v-else>
      <section class="filters page-card"><BaseSelect label="Panel" v-model="selectedPanelId"><option value="all">Comparar todos</option><option v-for="panel in panels" :key="panel.id" :value="panel.id">{{ panel.nombre }}</option></BaseSelect><BaseSelect label="Circuito" v-model="selectedCircuitId"><option value="all">Comparar todos</option><option v-for="circuit in circuitOptions" :key="circuit.id" :value="circuit.id">{{ circuit.nombre }}</option></BaseSelect><div class="scope-note"><span>Contexto activo</span><strong>{{ visibleRecords.length }} {{ visibleRecords.length === 1 ? 'circuito' : 'circuitos' }}</strong></div></section>
      <section v-if="!visibleRecords.length" class="page-card inline-empty"><strong>No hay circuitos para esta combinación.</strong><span>Prueba con otro panel o circuito.</span></section>
      <template v-else>
        <section v-for="record in visibleRecords" :key="record.circuit.id" class="measurement-group"><div class="group-heading"><div><span class="eyebrow">{{ record.panel.nombre }} · {{ record.device.nombre }}</span><h3>{{ record.circuit.nombre }}</h3></div><span class="group-state">{{ record.measurements.length ? 'Con mediciones' : 'Sin mediciones' }}</span></div><div class="metrics"><article v-for="metric in metrics" :key="metric.key" class="metric page-card"><span>{{ metric.label }}</span><strong>{{ formatMetric(record.latest?.[metric.key], metric.decimals) }}</strong><small>{{ metric.unit }}</small></article></div></section>
        <section class="charts-heading"><div><span class="eyebrow">Evolución de mediciones</span><h3>Últimos 10 minutos</h3></div><p>Las gráficas se actualizan con las mediciones guardadas y los eventos recibidos en tiempo real.</p></section>
        <section class="charts-grid"><RealtimeChart v-for="chart in charts" :key="chart.key" :title="chart.title" :unit="chart.unit" :explanation="chart.explanation" :series="chartSeries(chart.key)"/></section>
      </template>
    </template>
  </div>
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import BaseSelect from '../components/common/BaseSelect.vue';
import EmptyState from '../components/common/EmptyState.vue';
import ErrorState from '../components/common/ErrorState.vue';
import LoadingState from '../components/common/LoadingState.vue';
import StatusBadge from '../components/common/StatusBadge.vue';
import RealtimeChart from '../components/realtime/RealtimeChart.vue';
import { tiempoRealApi } from '../services/tiempoRealApi';
import { usePredioStore } from '../stores/predioStore';
import { useRealtimeStore } from '../stores/realtimeStore';

const predio=usePredioStore(); const realtime=useRealtimeStore();
const loading=ref(false); const loadError=ref(''); const panels=ref([]); const records=ref([]); const selectedPanelId=ref('all'); const selectedCircuitId=ref('all'); let requestVersion=0;
const metrics=[{key:'energia',label:'Energía',unit:'kWh',decimals:3},{key:'potencia',label:'Potencia',unit:'W',decimals:2},{key:'voltaje',label:'Voltaje',unit:'V',decimals:2},{key:'corriente',label:'Corriente',unit:'A',decimals:2},{key:'factor_potencia',label:'Factor de potencia',unit:'FP',decimals:3}];
const charts=[{key:'energia',title:'Energía',unit:'kWh',explanation:'Muestra cómo cambia la energía acumulada con el paso del tiempo.'},{key:'potencia',title:'Potencia',unit:'W',explanation:'Indica cuánta potencia se está utilizando en cada momento.'},{key:'voltaje',title:'Voltaje',unit:'V',explanation:'Permite observar la estabilidad del voltaje durante la medición.'},{key:'corriente',title:'Corriente',unit:'A',explanation:'Representa la corriente que circula por el circuito.'},{key:'factor_potencia',title:'Factor de potencia',unit:'FP',explanation:'Ayuda a interpretar qué tan eficientemente se utiliza la energía.'}];
const circuitOptions=computed(()=>records.value.filter((record)=>selectedPanelId.value==='all'||record.panel.id===selectedPanelId.value).map((record)=>({id:record.circuit.id,nombre:`${record.panel.nombre} · ${record.circuit.nombre}`})));
const visibleRecords=computed(()=>records.value.filter((record)=>(selectedPanelId.value==='all'||record.panel.id===selectedPanelId.value)&&(selectedCircuitId.value==='all'||record.circuit.id===selectedCircuitId.value)));
function formatMetric(value,decimals){return value===null||value===undefined||Number.isNaN(Number(value))?'—':Number(value).toLocaleString('es-CO',{minimumFractionDigits:decimals,maximumFractionDigits:decimals})}
function toMeasurement(item,time){return {id:item.id||`${time}-${item.circuito_id||item.circuito}`,created_at:time,circuito_id:item.circuito_id,potencia:Number(item.potencia),energia:Number(item.energia),voltaje:Number(item.voltaje),corriente:Number(item.corriente),factor_potencia:Number(item.factor_potencia)}}
function normalizeRecord(panel,device,circuit,measurements){const ordered=(measurements||[]).map((item)=>toMeasurement(item,item.created_at)).filter((item)=>Number.isFinite(new Date(item.created_at).getTime())).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));return {panel,device,circuit,measurements:ordered,latest:ordered.at(-1)||null}}
async function loadData(){const propertyId=predio.predioId.value;if(!propertyId)return;const version=++requestVersion;loading.value=true;loadError.value='';records.value=[];selectedPanelId.value='all';selectedCircuitId.value='all';try{const panelList=await tiempoRealApi.listarPaneles(propertyId);if(version!==requestVersion)return;panels.value=Array.isArray(panelList)?panelList:[];const built=[];for(const panel of panels.value){const devices=await tiempoRealApi.listarDispositivos(panel.id);for(const device of Array.isArray(devices)?devices:[]){const circuits=await tiempoRealApi.listarCircuitos(device.id);for(const circuit of Array.isArray(circuits)?circuits:[]){const from=new Date(Date.now()-10*60*1000).toISOString();const measurements=await tiempoRealApi.listarMediciones(circuit.id,from);built.push(normalizeRecord(panel,device,circuit,measurements));}}}if(version===requestVersion)records.value=built;}catch{if(version===requestVersion)loadError.value='No se pudo cargar la información de tiempo real. Intenta nuevamente.'}finally{if(version===requestVersion)loading.value=false}}
function applyLivePayload(payload){const time=payload?.timestamp||new Date().toISOString();for(const item of payload?.medidores||[]){const record=records.value.find((candidate)=>candidate.circuit.id===item.id_circuito);if(!record)continue;const measurement=toMeasurement(item,time);record.measurements=[...record.measurements.filter((old)=>old.id!==measurement.id),measurement].filter((old)=>Date.now()-new Date(old.created_at).getTime()<=10*60*1000).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));record.latest=record.measurements.at(-1)||null}}
function chartSeries(metric){return visibleRecords.value.map((record)=>({label:`${record.panel.nombre} · ${record.circuit.nombre}`,points:record.measurements.map((item)=>({time:item.created_at,value:item[metric]}))})).filter((series)=>series.points.length)}
watch(()=>predio.predioId.value,loadData);watch(()=>realtime.state.ultimaMedicion,applyLivePayload);watch(selectedPanelId,()=>{if(selectedCircuitId.value!=='all'&&!circuitOptions.value.some((item)=>item.id===selectedCircuitId.value))selectedCircuitId.value='all'});onMounted(loadData);onUnmounted(()=>{requestVersion++});
</script>

<style scoped>.realtime-view{display:grid;gap:20px}.welcome{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.eyebrow{color:var(--color-primary);font-size:10px;text-transform:uppercase;letter-spacing:.1em;font-weight:700}.welcome h2{color:#82b8ff;font-size:29px;margin-top:7px}.welcome p{color:var(--color-muted);margin-top:7px;font-size:13px}.filters{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px;padding:18px}.filters :deep(.field){gap:7px}.scope-note{display:grid;align-content:center;gap:6px;padding:0 14px;border-left:1px solid rgba(100,133,171,.2)}.scope-note span{color:var(--color-muted);font-size:11px}.scope-note strong{color:#dceaff;font-size:14px}.inline-empty{display:grid;gap:6px;padding:22px;color:var(--color-muted);font-size:13px}.inline-empty strong{color:#dceaff}.measurement-group{display:grid;gap:10px}.group-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.group-heading h3,.charts-heading h3{color:#c8ddfb;font-size:17px;margin-top:6px}.group-state{color:var(--color-muted);font-size:11px}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:11px}.metric{display:grid;gap:7px;text-align:center;padding:17px 10px}.metric span{color:#a8c8f2;font-size:11px;font-weight:600}.metric strong{font:700 21px var(--font-display);color:#fff;overflow-wrap:anywhere}.metric small{color:var(--color-muted);font-size:10px}.charts-heading{display:flex;align-items:end;justify-content:space-between;gap:18px;margin-top:5px}.charts-heading p{color:var(--color-muted);font-size:11px}.charts-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.charts-grid :deep(.chart-card:last-child){grid-column:1/-1}.status-badge{white-space:nowrap}@media(max-width:900px){.filters{grid-template-columns:1fr 1fr}.scope-note{border-left:0;padding:9px 0;border-top:1px solid rgba(100,133,171,.2);grid-column:1/-1}.metrics{grid-template-columns:repeat(3,1fr)}.charts-grid{grid-template-columns:1fr}.charts-grid :deep(.chart-card:last-child){grid-column:auto}}@media(max-width:560px){.welcome{display:block}.welcome :deep(.badge){margin-top:12px}.filters{grid-template-columns:1fr;padding:14px}.scope-note{grid-column:auto}.metrics{grid-template-columns:repeat(2,1fr)}.metric:last-child{grid-column:1/-1}.charts-heading{display:block}.charts-heading p{margin-top:8px}.group-heading{align-items:flex-start;display:block}.group-state{display:block;margin-top:8px}}
</style>
