<template>
  <div class="realtime-view">
    <header class="welcome"><div><span class="eyebrow">Monitoreo en vivo</span><h2>Tiempo real</h2><p>{{ predio.predioActual.value?.nombre || 'Selecciona un predio para comenzar' }}</p></div></header>
    <ErrorState v-if="loadError" :message="loadError" retry @retry="loadData"/>
    <LoadingState v-else-if="loading" message="Cargando paneles, circuitos y mediciones…"/>
    <EmptyState v-else-if="!predio.predioId.value" title="Selecciona un predio" message="Elige un predio en la barra superior para consultar sus mediciones."/>
    <EmptyState v-else-if="!records.length" title="Este predio aún no tiene circuitos" message="Cuando existan paneles, dispositivos y circuitos disponibles aparecerán aquí."/>
    <template v-else>
      <section class="filters page-card"><BaseSelect label="Panel" v-model="selectedPanelId"><option value="all" :disabled="!canComparePanels">{{ canComparePanels ? 'Comparar todos los paneles' : 'No hay suficientes paneles para comparar' }}</option><option v-for="panel in panels" :key="panel.id" :value="panel.id">{{ panelLabel(panel) }}</option></BaseSelect><BaseSelect label="Circuito" v-model="selectedCircuitId" :disabled="selectedPanelId === 'all' || !circuitOptions.length"><option value="all">{{ selectedPanelId === 'all' ? 'Selecciona un panel' : 'Comparar circuitos del panel' }}</option><option v-for="circuit in circuitOptions" :key="circuit.id" :value="circuit.id">{{ circuit.nombre }}</option></BaseSelect><BaseSelect label="Mostrar últimos" v-model="rangeMinutes"><option v-for="range in timeRanges" :key="range.value" :value="range.value">{{ range.label }}</option></BaseSelect><div class="scope-note"><span>Contexto activo</span><strong>{{ visibleRecords.length }} {{ visibleRecords.length === 1 ? 'circuito' : 'circuitos' }}</strong></div></section>
      <section v-if="!visibleRecords.length" class="page-card inline-empty"><strong>No hay circuitos para esta combinación.</strong><span>Prueba con otro panel o circuito.</span></section>
      <template v-else>
        <section v-for="record in visibleRecords" :key="record.circuit.id" class="measurement-group"><div class="group-heading"><div><span class="eyebrow">{{ panelLabel(record.panel) }} · {{ record.device.nombre }}</span><h3>{{ record.circuit.nombre }}</h3></div><span class="group-state">{{ record.measurements.length ? 'Con mediciones' : 'Sin mediciones' }}</span></div><div class="metrics"><article v-for="metric in metrics" :key="metric.key" class="metric page-card"><span>{{ metric.label }}</span><strong>{{ formatMetric(record.latest?.[metric.key], metric.decimals) }}</strong><small>{{ metric.unit }}</small></article></div></section>
        <section class="charts-heading"><div><span class="eyebrow">Evolución de mediciones</span><h3>Últimos {{ rangeMinutes }} minuto{{ rangeMinutes === 1 ? '' : 's' }}</h3></div><p>Las gráficas muestran cada lectura real recibida y se actualizan en tiempo real.</p></section>
        <section class="charts-grid"><RealtimeChart v-for="chart in charts" :key="chart.key" :title="chart.title" :unit="chart.unit" :explanation="chart.explanation" :series="chartSeries(chart.key)"/></section>
      </template>
    </template>
  </div>
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import BaseSelect from '../components/common/BaseSelect.vue';
import EmptyState from '../components/common/EmptyState.vue';
import ErrorState from '../components/common/ErrorState.vue';
import LoadingState from '../components/common/LoadingState.vue';
import RealtimeChart from '../components/realtime/RealtimeChart.vue';
import { tiempoRealApi } from '../services/tiempoRealApi';
import { usePredioStore } from '../stores/predioStore';
import { useRealtimeStore } from '../stores/realtimeStore';

const predio=usePredioStore(); const realtime=useRealtimeStore();
const loading=ref(false); const loadError=ref(''); const panels=ref([]); const records=ref([]); const selectedPanelId=ref('all'); const selectedCircuitId=ref('all'); const rangeMinutes=ref(1); const timeRanges=[{value:1,label:'1 minuto'},{value:2,label:'2 minutos'},{value:5,label:'5 minutos'}]; let requestVersion=0; let refreshTimer; let refreshing=false;
const metrics=[{key:'energia',label:'Energía',unit:'kWh',decimals:3},{key:'potencia',label:'Potencia',unit:'W',decimals:2},{key:'voltaje',label:'Voltaje',unit:'V',decimals:2},{key:'corriente',label:'Corriente',unit:'A',decimals:2},{key:'factor_potencia',label:'Factor de potencia',unit:'FP',decimals:3}];
const charts=[{key:'energia',title:'Energía consumida',unit:'kWh',explanation:'Muestra la energía reportada por cada circuito en cada lectura. Los huecos indican que no llegó una medición.'},{key:'potencia',title:'Potencia utilizada',unit:'W',explanation:'Muestra cuánta potencia se estaba utilizando en cada lectura. Un valor más alto indica mayor demanda en ese momento.'},{key:'voltaje',title:'Fuerza eléctrica',unit:'V',explanation:'Muestra la fuerza eléctrica registrada en cada lectura y permite observar si se mantiene estable.'},{key:'corriente',title:'Cantidad de electricidad',unit:'A',explanation:'Muestra cuánta electricidad circulaba por el circuito en cada lectura.'},{key:'factor_potencia',title:'Aprovechamiento eléctrico',unit:'FP',explanation:'Muestra qué tan bien se estaba aprovechando la electricidad en cada lectura.'}];
const canComparePanels=computed(()=>panels.value.length>1&&panels.value.filter((panel)=>records.value.some((record)=>record.panel.id===panel.id)).length>1);
const circuitOptions=computed(()=>selectedPanelId.value==='all'?[]:records.value.filter((record)=>record.panel.id===selectedPanelId.value).map((record)=>({id:record.circuit.id,nombre:record.circuit.nombre})));
const visibleRecords=computed(()=>records.value.filter((record)=>(selectedPanelId.value==='all'||record.panel.id===selectedPanelId.value)&&(selectedCircuitId.value==='all'||record.circuit.id===selectedCircuitId.value)));
function panelLabel(panel){return `${panel.nombre} · ${panel.tipo_panel==='Secundario'?'Panel secundario':'Panel principal'}`}
function formatMetric(value,decimals){return value===null||value===undefined||Number.isNaN(Number(value))?'—':Number(value).toLocaleString('es-CO',{minimumFractionDigits:decimals,maximumFractionDigits:decimals})}
function toMeasurement(item,time){return {id:item.id||`${time}-${item.circuito_id||item.circuito}`,created_at:time,circuito_id:item.circuito_id,potencia:Number(item.potencia),energia:Number(item.energia),voltaje:Number(item.voltaje),corriente:Number(item.corriente),factor_potencia:Number(item.factor_potencia)}}
function normalizeRecord(panel,device,circuit,measurements){const ordered=(measurements||[]).map((item)=>toMeasurement(item,item.created_at)).filter((item)=>Number.isFinite(new Date(item.created_at).getTime())).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));return {panel,device,circuit,measurements:ordered,latest:ordered.at(-1)||null}}
async function loadData(){const propertyId=predio.predioId.value;if(!propertyId)return;const version=++requestVersion;loading.value=true;loadError.value='';records.value=[];selectedPanelId.value='all';selectedCircuitId.value='all';try{const panelList=await tiempoRealApi.listarPaneles(propertyId);if(version!==requestVersion)return;panels.value=Array.isArray(panelList)?panelList:[];const built=[];for(const panel of panels.value){const devices=await tiempoRealApi.listarDispositivos(panel.id);for(const device of Array.isArray(devices)?devices:[]){const circuits=await tiempoRealApi.listarCircuitos(device.id);for(const circuit of Array.isArray(circuits)?circuits:[]){const from=new Date(Date.now()-5*60*1000-15000).toISOString();const measurements=await tiempoRealApi.listarMediciones(circuit.id,from);built.push(normalizeRecord(panel,device,circuit,measurements));}}}if(version===requestVersion){records.value=built;if(!canComparePanels.value&&panels.value.length)selectedPanelId.value=panels.value[0].id;}}catch{if(version===requestVersion)loadError.value='No se pudo cargar la información de tiempo real. Intenta nuevamente.'}finally{if(version===requestVersion)loading.value=false}}
async function refreshMeasurements(){if(refreshing||loading.value||!predio.predioId.value||!records.value.length)return;refreshing=true;try{const from=new Date(Date.now()-5*60*1000-15000).toISOString();const currentRecords=records.value.map((record)=>({...record}));const measurements=await Promise.all(currentRecords.map((record)=>tiempoRealApi.listarMediciones(record.circuit.id,from)));records.value=currentRecords.map((record,index)=>normalizeRecord(record.panel,record.device,record.circuit,measurements[index]));}catch{loadError.value='No se pudieron actualizar las mediciones. Se reintentará automáticamente.'}finally{refreshing=false}}
function applyLivePayload(payload){const time=payload?.timestamp||new Date().toISOString();for(const item of payload?.medidores||[]){const record=records.value.find((candidate)=>candidate.circuit.id===item.id_circuito);if(!record)continue;const measurement=toMeasurement(item,time);record.measurements=[...record.measurements.filter((old)=>old.id!==measurement.id),measurement].filter((old)=>Date.now()-new Date(old.created_at).getTime()<=5*60*1000+15000).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));record.latest=record.measurements.at(-1)||null}}
function chartSeries(metric){const cutoff=Date.now()-rangeMinutes.value*60*1000;return visibleRecords.value.map((record)=>{const seen=new Set();const points=record.measurements.map((item)=>{const time=new Date(item.created_at).getTime();const value=Number(item[metric]);const identity=item.id||`${time}-${item.circuito_id||record.circuit.id}`;if(seen.has(identity)||!Number.isFinite(time)||time<cutoff||!Number.isFinite(value))return null;seen.add(identity);return {time:new Date(time).toISOString(),value};}).filter(Boolean).sort((a,b)=>new Date(a.time)-new Date(b.time));return {label:`${panelLabel(record.panel)} · ${record.circuit.nombre}`,points};}).filter((series)=>series.points.length)}
watch(()=>predio.predioId.value,loadData);watch(()=>realtime.state.ultimaMedicion,applyLivePayload);watch(selectedPanelId,()=>{if(selectedPanelId.value==='all'||selectedCircuitId.value!=='all'&&!circuitOptions.value.some((item)=>item.id===selectedCircuitId.value))selectedCircuitId.value='all'});onMounted(()=>{loadData();refreshTimer=setInterval(refreshMeasurements,5000)});onUnmounted(()=>{requestVersion++;clearInterval(refreshTimer)});
</script>

<style scoped>.realtime-view{display:grid;gap:20px;min-width:0}.welcome{display:flex;align-items:flex-start;gap:20px}.eyebrow{color:var(--color-primary);font-size:11px;text-transform:uppercase;letter-spacing:.1em;font-weight:700}.welcome h2{color:#eaf3ff;font-size:30px;margin-top:7px}.welcome p{color:#d6e2f0;margin-top:7px;font-size:15px}.filters{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;padding:18px}.filters :deep(.field){gap:7px}.scope-note{display:grid;align-content:center;gap:6px;padding:0 14px;border-left:1px solid rgba(100,133,171,.2)}.scope-note span{color:#d6e2f0;font-size:13px}.scope-note strong{color:#fff;font-size:15px}.inline-empty{display:grid;gap:6px;padding:22px;color:#d6e2f0;font-size:14px}.inline-empty strong{color:#fff}.measurement-group{display:grid;gap:10px}.group-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.group-heading h3,.charts-heading h3{color:#e6f0fc;font-size:18px;margin-top:6px}.group-state{color:#d6e2f0;font-size:13px}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:11px}.metric{display:grid;gap:7px;text-align:center;padding:17px 10px}.metric span{color:#e8f1fb;font-size:13px;font-weight:600}.metric strong{font:700 22px var(--font-display);color:#fff;overflow-wrap:anywhere}.metric small{color:#d6e2f0;font-size:12px}.charts-heading{display:flex;align-items:end;justify-content:space-between;gap:18px;margin-top:5px}.charts-heading p{color:#d6e2f0;font-size:13px}.charts-grid{display:grid;grid-template-columns:minmax(0,1fr);gap:18px;width:100%;min-width:0}.charts-grid :deep(.chart-card){width:100%;min-width:0}@media(max-width:1050px){.filters{grid-template-columns:repeat(2,minmax(0,1fr))}.scope-note{border-left:0;padding:9px 0;border-top:1px solid rgba(100,133,171,.2)}}@media(max-width:900px){.metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.welcome{display:block}.filters{grid-template-columns:1fr;padding:14px}.scope-note{grid-column:auto}.metrics{grid-template-columns:repeat(2,1fr)}.metric:last-child{grid-column:1/-1}.charts-heading{display:block}.charts-heading p{margin-top:8px}.group-heading{align-items:flex-start;display:block}.group-state{display:block;margin-top:8px}}
</style>
